services:
  sas_db:
    image: postgres:15
    environment:
      POSTGRES_USER: sas
      POSTGRES_PASSWORD: sas
      POSTGRES_DB: sas
    ports:
      - "5432:5432"
    networks:
      - sas_network

  sas_backend:
    build: ./backend
    env_file:
      - ./backend/.env.auth
    ports:
      - "8000:8000"
    depends_on:
      - sas_db
    networks:
      - sas_network

networks:
  sas_network:
    driver: bridge
